version: '3.1'

services:
  db_open_shop:
    image: kartoza/postgis:12.0
    restart: always
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: open_data
      POSTGRES_PASSWORD: 0808ee1360fd717cb5a23961ddc3863f

  backend:
    image: open_shop_map:latest
    restart: always
    ports:
        - 8000:8000
    links: 
        - "db_open_shop:database"
    depends_on: 
        - db_open_shop