version: '3.1'

services:
  db_open_shop:
    image: kartoza/postgis:12.0
    restart: always
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: open_data
      POSTGRES_PASSWORD: 0808ee1360fd717cb5a23961ddc3863f
 
  backend:
    build: .
    restart: always
    # volumes:
        #- ./rust-backend/log:/home/app/rust-backend/log/
        # - ./rust-backend/certs:/home/app/rust-backend/certs/
    ports:
        - 8080:8080
        - 8443:8443
    links: 
        - "db_open_shop:database"
    depends_on: 
        - db_open_shop
